### ISSUE TITLE
Bad credentials err

### ISSUE THREAD

**Issue by whxyu1337** [IgorKowalczyk/igorkowalczyk#28]
Idk how to deal w/ this error
`Error: Bad credentials
✖  fatal     HttpError: Bad credentials 
    at /home/runner/work/whxyu1337/whxyu1337/node_modules/.pnpm/@octokit+request@5.6.3/node_modules/@octokit/request/dist-node/index.js:86:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///home/runner/work/whxyu1337/whxyu1337/src/updaters/fetch_activities.js:63:19
 ELIFECYCLE  Command failed with exit code 1.
Error: Process completed with exit code 1.`

**Comment by IgorKowalczyk** [comment]
To properly run workflow [(main.yml)](https://github.com/IgorKowalczyk/igorkowalczyk/blob/master/.github/workflows/main.yml) you need to set PAT ([Personal Access Token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token)) with the name `GH_TOKEN` in the repository settings.

- Go to repository settings
- Scroll down to `Secrets` tab and click `Actions`
- Create new repository secret named `GH_TOKEN`

![image](https://user-images.githubusercontent.com/49127376/208461166-aeafeba1-d64a-45a3-9463-a11d7841015e.png)

PAT should include `user` and `repo` scopes

**Comment by whxyu1337** [comment]
> To properly run workflow [(main.yml)](https://github.com/IgorKowalczyk/igorkowalczyk/blob/master/.github/workflows/main.yml) you need to set PAT ([Personal Access Token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token)) with the name `GH_TOKEN` in the repository settings.
> 
> * Go to repository settings
> * Scroll down to `Secrets` tab and click `Actions`
> * Create new repository secret named `GH_TOKEN`
> 
> ![image](https://user-images.githubusercontent.com/49127376/208461166-aeafeba1-d64a-45a3-9463-a11d7841015e.png)
> 
> PAT should include `user` and `repo` scopes
I accidentally put my old gh token so its the reason main.yml is not working lol

**Comment by IgorKowalczyk** [comment]
Token of the bot/user account that has access to this repository
